shell_integration no-rc no-cursor
active_border_color #31748f
active_tab_background #26233a
active_tab_foreground #e0def4
background #191724
color0 #26233a
color1 #eb6f92
color10 #6feb87
color11 #f6c177
color12 #1072d2
color13 #c4a7e7
color14 #6ad3ec
color15 #e0def4
color2 #6feb87
color3 #f6c177
color4 #1072d2
color5 #c4a7e7
color6 #6ad3ec
color7 #e0def4
color8 #6e6a86
color9 #eb6f92
confirm_os_window_close 0
cursor #524f67
cursor_shape block
cursor_text_color #e0def4
font_family family="JetbrainsMono Nerd Font" features=""
font_size 14
foreground #e0def4
inactive_border_color #403d52
inactive_tab_background #191724
inactive_tab_foreground #6e6a86
initial_window_height 700
initial_window_width 1200
remember_window_size yes
selection_background #403d52
selection_foreground #e0def4

tab_bar_style powerline

url_color #c4a7e7
