wallpaper {
    monitor = VGA-1
    path = ~/wallpapers/batman-logo.jpg
    fit_mode = cover
}

splash = true

# .. more preloads

#set the default wallpaper(s) seen on initial workspace(s) --depending on the number of monitors used
#if more than one monitor in use, can load a 2nd image
# .. more monitors

#enable splash text rendering over the wallpaper

#fully disable ipc
# ipc = off

